require "./continios_integration.rb"
task :default, :config do |task, args|
  puts "ContiniOS Integration Build Process Did Launch"
  config_file = (args[:config].nil?) ? "configs/config.yml" : args[:config]
  task_runner = ContiniOSIntegration::CITaskRunner.instance
  task_runner.init_with_config(config: config_file)
  task_runner.run_tasks
  task_runner.on_completion
end